"""create user refresh token table

Revision ID: 0da4e49bec16
Revises: 3c6e3f56dbf4
Create Date: 2024-09-03 15:10:29.069902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da4e49bec16'
down_revision: Union[str, None] = '3c6e3f56dbf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshtoken.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'refresh_token_id'),
    sa.UniqueConstraint('user_id', 'refresh_token_id')
    )
    op.drop_constraint('session_refresh_token_id_fkey', 'session', type_='foreignkey')
    op.drop_column('session', 'refresh_token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('session_refresh_token_id_fkey', 'session', 'refreshtoken', ['refresh_token_id'], ['id'])
    op.drop_table('user_refresh_token')
    # ### end Alembic commands ###
