"""Correction of PR comments.

Revision ID: 317d5f994600
Revises: 0ecb8e4f73de
Create Date: 2024-08-27 11:06:26.101396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '317d5f994600'
down_revision: Union[str, None] = '0ecb8e4f73de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_user_id_fkey', 'session', type_='foreignkey')
    op.drop_constraint('session_refresh_token_id_fkey', 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key(None, 'session', 'refresh_token', ['refresh_token_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.create_unique_constraint(None, 'user_role', ['user_id', 'role_id'])
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['id'], referent_schema='auth')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'], referent_schema='auth')
    op.drop_column('user_role', 'updated_at')
    op.drop_column('user_role', 'id')
    op.drop_column('user_role', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user_role', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_role', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_role', type_='unique')
    op.drop_constraint(None, 'session', schema='auth', type_='foreignkey')
    op.drop_constraint(None, 'session', schema='auth', type_='foreignkey')
    op.create_foreign_key('session_refresh_token_id_fkey', 'session', 'refresh_token', ['refresh_token_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('session_user_id_fkey', 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
