"""remove unique constrain from user_agent field in Session table

Revision ID: 3c6e3f56dbf4
Revises: e968b6c83b5d
Create Date: 2024-09-03 11:33:45.138921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6e3f56dbf4'
down_revision: Union[str, None] = 'e968b6c83b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_user_agent_key', 'session', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_user_agent_key', 'session', ['user_agent'])
    # ### end Alembic commands ###
