"""remove user salt column

Revision ID: e968b6c83b5d
Revises: cb9dda281d95
Create Date: 2024-09-02 21:28:23.715617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e968b6c83b5d'
down_revision: Union[str, None] = 'cb9dda281d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    op.create_unique_constraint(None, 'user_role', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='unique')
    op.add_column('user', sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
