name: Auth CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2.5
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: setup-poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH

      - name: dependencies
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: autopep8
        run: autopep8

      - name: hadolint
        uses: hadolint/hadolint-action@v2.0.0
        run: hadolint Dockerfile PostgresDockerfile

      - name: wemake-python-styleguide
        run: wemake-python-styleguide

      - name: isort
        uses: isort

      - name: test
        run: pytest tests