name: Hadolint

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Извлечение кода из репозитория
        uses: actions/checkout@v2

      - name: Установка Hadolint
        uses: hadolint/hadolint-action@v2.0.0

      - name: Проверка докер файлов
        run: hadolint Dockerfile PostgresDockerfile
