name: Wemake Python Styleguide and autopep8

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  stylecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.19.2
        with:
          args: .
          fail_on_error: false  # Позволяет продолжить, даже если есть ошибки

      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --recursive --in-place --aggressive --aggressive .

      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1

      - name: isort
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "pyproject.toml"
