name: Wemake Python Styleguide

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  stylecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.19.2
        with:
          args: .  # Укажите директорию, которую хотите проверить
